<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>NeonGyro</RootNamespace>
		<AssemblyName>NeonGyro</AssemblyName>
		<LangVersion>default</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>embedded</DebugType>
		<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
		
		<GameDir Condition="$([MSBuild]::IsOSPlatform('Windows'))">C:\Program Files (x86)\Steam\steamapps\common\Neon White</GameDir>
        <GameDir Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(HOME)/.steam/steam/steamapps/common/Neon White</GameDir>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="$(GameDir)\Neon White_Data\Managed\*.dll" Private="false" />
		<Reference Include="$(GameDir)\MelonLoader\net472\*.dll" Private="false" />
	</ItemGroup>

	<ItemGroup>
		<None Update="SDL3.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
